import Database from "better-sqlite3";
const db = new Database("data/united.db", { readonly: true });
const q = (sql: string) => db.prepare(sql).get() as Record<string, unknown>;
console.log("matches_with_lineups:", q("SELECT value v FROM meta WHERE key='matches_with_lineups'").v);
console.log("assists:", q("SELECT COUNT(*) n FROM match_events WHERE assist_player_id IS NOT NULL").n);
console.log("events:", q("SELECT COUNT(*) n FROM match_events").n);
console.log("goal events:", q("SELECT COUNT(*) n FROM match_events WHERE type IN ('goal','pen-goal')").n);
console.log("players:", q("SELECT COUNT(*) n FROM players").n);
console.log("matches:", q("SELECT COUNT(*) n FROM matches").n);
console.log("finals:", q("SELECT COUNT(*) n FROM matches WHERE round='Final'").n);
const finals = db.prepare("SELECT id, season, competition_id FROM matches WHERE round='Final' ORDER BY date").all();
console.log(finals);
